### ISSUE TITLE
Visual result

### ISSUE THREAD

**Issue by ZiMo-Chen** [sail-sg/iFormer#2]
Hello, I am very interested in your work. Could you please provide me with the visualized code of Figure A and Figure B in Figure 1?

**Comment by ChenyangSi** [comment]
@cxq1 thanks!  relative log amplitudes are plotted with https://colab.research.google.com/github/xxxnell/how-do-vits-work/blob/transformer/fourier_analysis.ipynb. Fourier spectrum of feature maps is visualized with the function np.fft.fft2()

**Comment by ZiMo-Chen** [comment]
> @cxq1 thanks! relative log amplitudes are plotted with https://colab.research.google.com/github/xxxnell/how-do-vits-work/blob/transformer/fourier_analysis.ipynb. Fourier spectrum of feature maps is visualized with the function np. fft.fft2()
Thank you for your contribution. Could you also provide the code visualized in other pictures in the paper, such as the Hessian maximum eigenvalue spectrum

**Comment by ChenyangSi** [comment]
@cxq1 did you mean the  visualization of Grad-CAM activation maps？

**Comment by ZiMo-Chen** [comment]
> @cxq1 did you mean the visualization of Grad-CAM activation maps？

yes,  
Thank you for your reply. I have another question. Can "Avepool" and "upsample" be regarded as low-frequency

**Comment by snowcement** [comment]
@ChenyangSi Hello, I'm very interested in visualization of your Fourier spectrum. You said Fourier spectrum of feature maps is visualized with the function np.fft.fft2(). However, the dimensions of feature maps obtained by different layers/components are different. It seems that the dimensions of MaxPool, DwConv and Attention in Figure. 4(a) are indeed the same. I wonder what the visual code looks like.

**Comment by shangshang0912** [comment]
您的邮件已经收到。我会及时做出回复。

**Comment by hzlbbfrog** [comment]
@ChenyangSi 
Hi! I am also interested in the visualization of Figure 1(a) and Figure 4.
I want to know if you will release some code about the visualization of Fourier spectrum for feature maps with different  channels. (do a channel-wise average pooling?)
Thank you so much!

**Comment by ChenyangSi** [comment]
@hzlbbfrog yes, first do FFT with fft2(), then do a channel-wise average pooling

**Comment by ChenyangSi** [comment]
@cxq1 Grad-CAM: https://github.com/sail-sg/poolformer/blob/main/misc/cam_image.py 

yes, "Avepool" and "upsample" can be regarded as low-frequency, but we use these two operations mainly to reduce the computational cost.

**Comment by ChenyangSi** [comment]
@snowcement  Yes, the outputs of Conv, maxpool and attention have different channel dimensions. We first do FFT with fft2() for each channel, then do a channel-wise average pooling.
