### ISSUE TITLE
Replicate

### ISSUE THREAD

**Issue by ZiMo-Chen** [sail-sg/iFormer#7]
Hello, thank you for your work. I am very interested in your work and would like to reproduce your code. Is there anything special about your code when it is implemented

**Comment by Ga-Lee** [comment]
> Hello, thank you for your work. I am very interested in your work and would like to reproduce your code. Is there anything special about your code when it is implemented

Hello,bro
How is your reproduce plan going?
Can you tell me the implement for the maxpooling+linear branch of the high-frequency mixer?
I feel confused how this branch keep the feature map through it the same size even after the pool operation.
Can you tell me the configuration details for the branch?
Thank you a lot !

**Comment by Allenem** [comment]
> > Hello, thank you for your work. I am very interested in your work and would like to reproduce your code. Is there anything special about your code when it is implemented
> 
> Hello,bro How is your reproduce plan going? Can you tell me the implement for the maxpooling+linear branch of the high-frequency mixer? I feel confused how this branch keep the feature map through it the same size even after the pool operation. Can you tell me the configuration details for the branch? Thank you a lot !

I have tried to implement the operation for h1. I think you must add **upsample** operation after maxpool+linear, or use linear only. Or if you only use maxpool+linear, the shape of image will be not the same as outputs of other channels(h2 & low-frequency). Personal understanding, for reference only.

**Comment by Ga-Lee** [comment]
> > > Hello, thank you for your work. I am very interested in your work and would like to reproduce your code. Is there anything special about your code when it is implemented
> > 
> > 
> > Hello,bro How is your reproduce plan going? Can you tell me the implement for the maxpooling+linear branch of the high-frequency mixer? I feel confused how this branch keep the feature map through it the same size even after the pool operation. Can you tell me the configuration details for the branch? Thank you a lot !
> 
> I have tried to implement the operation for h1. I think you must add **upsample** operation after maxpool+linear, or use linear only. Or if you only use maxpool+linear, the shape of image will be not the same as outputs of other channels(h2 & low-frequency). Personal understanding, for reference only.

Thank you for your reply. I had reproduced this branch  according to the way in which Inception V1 operates—— I set padding = 1 to keep the size of feature map constant when pooling , I  am not sure whether it is reasonable.  Orz

**Comment by Ga-Lee** [comment]
> > > Hello, thank you for your work. I am very interested in your work and would like to reproduce your code. Is there anything special about your code when it is implemented
> > 
> > 
> > Hello,bro How is your reproduce plan going? Can you tell me the implement for the maxpooling+linear branch of the high-frequency mixer? I feel confused how this branch keep the feature map through it the same size even after the pool operation. Can you tell me the configuration details for the branch? Thank you a lot !
> 
> I have tried to implement the operation for h1. I think you must add **upsample** operation after maxpool+linear, or use linear only. Or if you only use maxpool+linear, the shape of image will be not the same as outputs of other channels(h2 & low-frequency). Personal understanding, for reference only.

Thank you for your reply. I had reproduced this branch  according to the way in which Inception V1 operates—— I set padding = 1 to keep the size of feature map constant when pooling , I  am not sure whether it is reasonable.  Orz
